name: First Workflow

on:
  push:
    branches:
      - main

jobs:
  hello:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: List Files
        run: ls

      - name: Print Message
        run: echo "Hello from GitHub Actions"
