name: Practice Workflow

on:
  push:
    branches:
      - main

jobs:
  practice:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Current Directory
        run: pwd

      - name: List Files
        run: ls -la

      - name: Node Version
        run: node -v

      - name: Python Version
        run: python --version

      - name: Custom Message
        run: echo "I started GitHub Actions journey"
